# Generated by Django 2.2.1 on 2019-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('birth', models.DateTimeField()),
                ('nationality', models.CharField(choices=[('KR', '한국'), ('JP', '일본'), ('TW', '대만')], max_length=20)),
                ('position', models.TextField()),
            ],
        ),
    ]
