# Generated by Django 2.2.1 on 2019-05-24 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_twice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
