# Generated by Django 2.2.1 on 2019-05-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twice',
            name='nationality',
            field=models.CharField(choices=[('KR', '대한민국'), ('JP', '일본'), ('TW', '대만')], max_length=20),
        ),
    ]
